### ISSUE TITLE
Generate an assignment with a config file that fails the GatorGradle run if a single checks fail

### ISSUE THREAD

**Issue by kailaniwoodard** [cmpsc-481-s22-m1/ConfiGator#1]
**User Story**:
As a... GatorGradle user, I want to...
generate an assignment with a config file that fails the GatorGradle run if any checks fail.

**Implementation Plans**:
Use fail-fast logic with Gradle's native configuration option to fail the GatorGradle run if a single checks fail.

**Relevant Resources**:
[Gradle `Test` Documentation](https://docs.gradle.org/current/dsl/org.gradle.api.tasks.testing.Test.html)

**Comment by donizk** [comment]
failFast = false 

command will fail the first test failure

**Comment by Michionlion** [comment]
Hey @donizk, I think you may be confusing the testing abilities of Gradle with GatorGradle itself; the "fail immediately" logic of GatorGradle is configured by the parameter `fastfail: false` in the header of the `config/gatorgrader.yml` configuration file. See the GatorGradle [documentation](https://github.com/GatorEducator/gatorgradle#configuring-checks).

**Comment by donizk** [comment]
work with Adam, Peter, and Kevin to see who will develop cli and possibly employing write to file capabilities python has to generate yml file

ref:
 [create text file using python](https://www.pythontutorial.net/python-basics/python-create-text-file/)

**Comment by donizk** [comment]
Code does generate a gatorgrader file, need to nestle it into a config file directory I will create using [this tutorial](https://www.geeksforgeeks.org/create-a-directory-in-python/). work on testing.
