### ISSUE TITLE
Generate an assignment with a config file that uses a given indentation size

### ISSUE THREAD

**Issue by kailaniwoodard** [cmpsc-481-s22-m1/ConfiGator#2]
**User Story**:
As a... GatorGradle user, I want to...
generate an assignment with a config file that uses a given indentation size.

**Implementation Plans**:
- Use Gradle's native(??) indent configuration with "lvl 2"
*or*
- Potentially implement [Spotless](https://github.com/diffplug/spotless) or something similar to fix indentation and catch improper indentation.

**Relevant Resources**:
[diffplug/spotless](https://github.com/diffplug/spotless)

**Comment by Michionlion** [comment]
@kailaniwoodard The "indentation" user story refers to the `indent` header parameter of GatorGradle's [configuration file](https://github.com/GatorEducator/gatorgradle#configuring-checks), `config/gatorgrader.yml`.
