### ISSUE TITLE
Refactor create_gatorgrader_yml to accept inputs

### ISSUE THREAD

**Issue by donizk** [cmpsc-481-s22-m1/ConfiGator#40]
Refactor code to take in input using [Typer](https://typer.tiangolo.com/) and write corresponding tests.

Make sure to take in input (if applicable to your file):
- gator grader version
- gator gradle version
- build breaks if test passes
- assignment name

----

Working on implementing the following user stories:

- Generate an assignment with a config file that fails the GatorGradle run if any checks fail

- Generate an assignment with a working GatorGradle installation

- Generate an assignment that has the simplest possible config file

- Generate an assignment with a config file that has a reasonable default assignment name

- Generate an assignment with a config file that fails the GatorGradle run if any checks fail

**Comment by Michionlion** [comment]
Just to clarify what we talked about this morning: You should be refactoring `main.py`, not `create_gatorgrader_yml`, since `main.py` is where you will need to call the `build.gradle` and GitHub Actions generation as well, with the user-provided data, as well.

**Comment by kailaniwoodard** [comment]
Note from Maria: Typer is (potentially?) sensitive to naming conventions...?
