### ISSUE TITLE
make a CLI for main.py

### ISSUE THREAD

**Issue by Kevin487** [cmpsc-481-s22-m1/ConfiGator#41]
To take in input that will be taken to the other methods to create the config files

& write the corresponding tests

**Comment by Kevin487** [comment]
minimum requirement:
- specify gator grader version (gator grader yml)
- specify gator gradle version
- specfiy build breaks if test passes
- specify assignment name

and test cases for all things

**Comment by donizk** [comment]
[Typer Command Docs](https://typer.tiangolo.com/tutorial/commands/options/) use this ref to prompt user for input and set default values

**Comment by donizk** [comment]
[Sample CLI](https://typer.tiangolo.com/typer-cli/)
