### ISSUE TITLE
Generate an assignment with a config file that uses a given "startup" script or command

### ISSUE THREAD

**Issue by kailaniwoodard** [cmpsc-481-s22-m1/ConfiGator#6]
**User Story:**
As a... GatorGradle user, I want to...
generate an assignment with a config file that uses a given "startup" script or command.

**Proposed Plan:**
Research scripts and command implementation to `gradle.properties` file.

**Comment by Michionlion** [comment]
@kailaniwoodard The "startup" script user story refers specifically to configuring the `startup` header parameter in the `config/gatorgrader.yml` configuration file. See the GatorGradle [documentation](https://github.com/GatorEducator/gatorgradle#configuring-checks) for an example. `gradle.properties` is probably not relevant for this user story.

**Comment by Kevin487** [comment]
Kind of important, but can be done at the very end if we have time
